[build]
  command = "npm run netlify:build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@nestjs/microservices", "@nestjs/websockets", "class-transformer", "class-validator", "pg", "pg-native"]
  included_files = ["dist/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false

[functions]
  directory = "netlify/functions"