[build]
  command = "npm run netlify:build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Include packages that are dynamically required by Nest
  external_node_modules = [
    "class-validator",
    "class-transformer",
    "@nestjs/microservices",
    "@nestjs/websockets"
  ]
  included_files = [
    "node_modules/class-validator/**",
    "node_modules/class-transformer/**",
    "node_modules/pg/**",
    "node_modules/pg-pool/**",
    "node_modules/pg-types/**",
    "node_modules/pg-protocol/**",
    "dist/**"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false