[build]
  command = "npm run netlify:build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Do not externalize pg so it's bundled automatically
  external_node_modules = [
    "class-validator",
    "class-transformer",
    "pg",
    "pg-pool",
    "pg-types",
    "pg-protocol"
  ]
  included_files = ["dist/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false