[build]
  command = "npm run netlify:build"
  functions = "dist/netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[functions]
  # CRITICAL: Change this back to "none"
  node_bundler = "none"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 4000
  port = 8888
  autoLaunch = false