[build]
  command = "npm run netlify:build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"
  # Force npm instead of pnpm
  NPM_FLAGS = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 4000
  port = 8888
  autoLaunch = false